# Generated by Django 3.2.7 on 2021-11-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sighting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sighting',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(verbose_name='Sighting Date'),
        ),
    ]
