# Generated by Django 3.2.7 on 2021-11-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211129_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='snacks',
            field=models.ManyToManyField(to='main_app.Snacks'),
        ),
    ]
